### ISSUE TITLE
Clarification about SportBukkit/SportPaper

### ISSUE THREAD

**Issue by Brottweiler** [SpiritenHasArrived/Spiriten.cf#16]
>SportBukkit : SportBukkit is a 1.12.2 (I think) fork of CraftBukkit improving stability and adding some new features. It was developed for and by the StratusNetwork server.

SportBukkit was created by and for the Overcast Network. When Overcast Network closed, the main plugin [PGM 1.12](https://github.com/OvercastNetwork/ProjectAres) was open sourced so now anyone could run their plugins, and SportBukkit was required. Stratus Network was one out of several servers who forked the projects.

>SportPaper : SportPaper is a 1.8.8 fork of Paper improving performance even more. It is developed for and by the StratusNetwork server.

SportPaper was developed by ElectroidFilms, a single person, to run the [PGM 1.8](https://github.com/PGMDev/PGM) plugin, which is an earlier version of the PGM plugin for before 1.9 came out. Several servers are running SportPaper when using the PGM plugin.

---

I'd do a PR and I might, but I didn't know how to format it, and another problem is that you link to a fork with additional changes (sometimes bad changes).

**Comment by Brottweiler** [comment]
Ok I made a PR here https://github.com/SpiritenHasArrived/Spiriten.cf/pull/17

**Comment by SpiritenHasArrived** [comment]
Accepted the PR, thank you for making it. I've forgotten about this repository for the most part and will soon update a lot once back from vacation.
