### ISSUE TITLE
Cyperhost Incorrect information

### ISSUE THREAD

**Issue by theepicsaxguy** [SpiritenHasArrived/Spiriten.cf#5]
Cyperhost does not offer unmetered cpu usage. You can see that very clearly when placing an order.

**Comment by SpiritenHasArrived** [comment]
Hi there

Fiirst off I'd like to say understand that I'm a single person who researched all of this with no help. Being rude won't help much and won't make me work faster on it

Secondly, I will not be changing this unless their support responds to my email confirming this. All of their advertising material on forums such as MCMarket states what I wrote. 

Have a nice day :)

**Comment by theepicsaxguy** [comment]
Not my intention to sound rude. Just wanted to share my knowledge. 

Have a great day :)
